### ISSUE TITLE
Issue when using explicitly implemented interface

### ISSUE THREAD

**Issue by jasonwoods-7** [Fody/Freezable#4]
When you create an interface such as

``` c#
	interface IFoo
	{
		string Bar { get; set; }
		string Baz { get; set; }
	}
```

and create a class implementing the IFoo and IFreezable interfaces such as

``` c#
	class FooImpl : IFoo, IFreezable
	{
		bool _isFrozen;

		string IFoo.Bar { get; set; }
		public string Baz { get; set; }

		public void Freeze()
		{
			_isFrozen = true;
		}
	}
```

the generated code becomes

``` c#
	internal class FooImpl : IFoo, IFreezable
	{
		private volatile bool _isFrozen;

		string IFoo.Bar { get; set; }

		public string Baz
		{
			[CompilerGenerated]
			get
			{
				return this.<Baz>k__BackingField;
			}
			[CompilerGenerated]
			set
			{
				this.CheckIfFrozen();
				this.<Baz>k__BackingField = value;
			}
		}

		public void Freeze()
		{
			this._isFrozen = true;
		}

		protected void CheckIfFrozen()
		{
			if (this._isFrozen)
			{
				throw new InvalidOperationException("Attempted to modify a frozen instance");
			}
		}
	}
```

As you can see, when using an explicitly implemented property, the CheckIfFrozen call is not added to the set method on the Bar property.

So, the following code would not throw the exception

``` c#
	void Test()
	{
		IFoo foo = new FooImpl
		{
			Bar = "bar",
			Baz = "baz"
		};
		(foo as IFreezable)?.Freeze();
		foo.Bar = "buzz";
	}
```

I'm guessing this is done because the property has a private scope, but is there a way to be able to check if the property is explicitly implementing an interface and add the CheckIfFrozen call?

**Comment by jasonwoods-7** [comment]
I looked into the code and found that it is skipping weaving when the property's scope is private.

Looks like line 36 of [TypeProcessor.cs](https://github.com/Fody/Freezable/blob/master/Fody/TypeProcessor.cs#L36) could be changed to
``` c#
  if (setMethod.IsPrivate && -1 == property.Name.IndexOf('.'))
```

I forked the project and made this [change](https://github.com/jasonwoods-7/Freezable/commit/92b0bc96e29a464169c97c8c3ede3057aa96366e).  Want a PR?

**Comment by SimonCropp** [comment]
Sure , send me a pr

**Comment by SimonCropp** [comment]
should be on nuget now
